version: "2.4"
services:
  webserver:
    env_file:
      - .env
    container_name: dagster_webserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    entrypoint: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
    volumes:
      - "./.dagster/storage:/opt/dagster/storage"
      - "./.dagster/local:/opt/dagster/local"
      - "./.dagster/compute_logs:/opt/dagster/compute_logs"
      - "./src:/opt/dagster/app/src"
      - "./data:/opt/dagster/app/data"
    ports:
      - "3000:3000"
    networks:
      - dagster_network

  daemon:
    env_file:
      - .env
    container_name: dagster_daemon
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    entrypoint: ["dagster-daemon", "run"]
    volumes:
      - "./.dagster/storage:/opt/dagster/storage"
      - "./.dagster/local:/opt/dagster/local"
      - "./.dagster/compute_logs:/opt/dagster/compute_logs"
      - "./src:/opt/dagster/app/src"
      - "./data:/opt/dagster/app/data"
    networks:
      - dagster_network

networks:
  dagster_network: